POST http://localhost:3000/
Content-Type: application/json

{
  "version": "1.0",
  "request": {
    "type": "IntentRequest",
    "requestId": "amzn1.echo-api.request.1",
    "timestamp": "2019-03-21T22:32:09Z",
    "locale": "en-US",
    "intent": {
      "name": "AskWeatherIntent",
      "confirmationStatus": "NONE",
      "slots": {
        "firstName": {
          "name": "firstName",
          "value": "Emily",
          "confirmationStatus": "NONE"
        },
        "favoriteColor": {
          "name": "favoriteColor",
          "confirmationStatus": "NONE"
        }
      }
    },
    "dialogState": "STARTED"
  },
  "session": {},
  "context": {}
}